# Generated by Django 5.0.6 on 2024-06-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedant_medical',
            name='datehepvirb',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='datehepvirc',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='datehepvird',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='datransing',
            field=models.DateField(blank=True),
        ),
    ]
