# Generated by Django 5.0.6 on 2024-06-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_web', '0002_alter_antecedant_medical_datehepvirb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedant_medical',
            name='dosevha',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='dosevhb',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='precisionautre',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
