# Generated by Django 5.0.6 on 2024-06-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_web', '0003_alter_antecedant_medical_dosevha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedant_medical',
            name='autre',
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='dosevha',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='dosevhb',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
