# Generated by Django 5.0.6 on 2024-06-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_web', '0004_remove_antecedant_medical_autre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedant_genecologique',
            name='datecesarienne',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_genecologique',
            name='datederniereregle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_genecologique',
            name='gestite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_genecologique',
            name='parite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
