# Generated by Django 5.0.6 on 2024-06-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_web', '0006_alter_antecedant_familial_autre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedant_chirurgical',
            name='dateavp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_chirurgical',
            name='datoperachir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='datehepvirb',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='datehepvirc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='datehepvird',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='datransing',
            field=models.DateField(blank=True, null=True),
        ),
    ]
