# Generated by Django 5.0.6 on 2024-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_web', '0005_alter_antecedant_genecologique_datecesarienne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedant_familial',
            name='autre',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='autresignephysique',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='conscience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='flechehepatique',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='statutoms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='dosevha',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='dosevhb',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='precisionautre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
