# Generated by Django 4.2.13 on 2024-06-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli_web', '0007_alter_antecedant_chirurgical_dateavp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='hospitalisation',
        ),
    ]
